version: '2.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_octane_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./.env:/var/www/.env
    env_file:
      - .env
    restart: unless-stopped
