version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_octane
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_octane
    ports:
      - "3306:3306"
    environment: MYSQL_DATABASE=mbg_12903 MYSQL_USER=root MYSQL_PASSWORD=dua3January20duatiga MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
