version: '2.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_octane_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./.env:/var/www/.env # mount file .env ke dalam container
    env_file:
      - .env # ini otomatis inject semua variabel dari .env
